Отображает фотографии других пользователей
htmlacademy-javascript/1970833-kekstagram-26 pull request #5
Opened 2022-06-19 13:43 UTC by andy-about-andy

Алексей в моём понимании тут http://joxi.net/gmvLoMwieOWO6A должно быть не textContent, а другое свойство. Так как в html что-то пошло не так http://joxi.net/bmoDpywtOZYKl2 . Нужна помощь)

2022-06-19 22:53 UTC, Zakamsky requested changes
![image](https://user-images.githubusercontent.com/35491086/174503231-102c00a3-fd83-4e38-a2df-00fe25acc6eb.png)
![image](https://user-images.githubusercontent.com/35491086/174503237-9ef13825-964a-4db0-9884-798b66123311.png)

У нас кроме комментов есть еще проблемка. Фото тоже не отрисовались. Если заглянуть в консоль и посмотреть где он ищет картинки, где они на самом деле лежат, и какой путь должен был быть в данных по тз прошлого урока, станет понятно в чем проблема.

2022-06-19 22:53 UTC, Zakamsky commented on js/rendering-thumbnails.js
> +  picture.querySelector('.picture__comments').textContent = comments;
Ты верно понял в какой строке проблема, но не точно понял причину. В целом ты почти нашел ответ.
на будущее, когда сталкиваешься с такими вещами:
1. выводишь элемент в консоль и понимаешь что это то что нужно
2. передаешь туда строку текста что бы убедиться что работает твой код.
3. выводишь в консоль то что ранее передавал и видишь причину проблемы...

давай вспомним, такую картину мы уже обсуждали в чате - это результат приведения объекта к строке.  так получилось потому что вставить в `textContent` можно только строку и js привел данные к строке.

Но проблема не в свойстве. Оно правильное. 
по заданию нам надо кол-во комментариев тут показать а мы туда суем массив... я уверен что ты знаешь как получить кол-во элементов массива, что бы вывести их в этом элементе.

upd: ты молодец что написал вопрос, на будущее - ты можешь точно так же как я пишу это комментарий выделить в файле нужные строки и написать комментарий к ним.
скрин можно вставить прямо в коммент из буфера обмена. гитхаб просто кладезь для совместной работы.

![image](https://user-images.githubusercontent.com/35491086/174503064-1f9d73a6-1ca1-419e-92a9-5c4ab606444e.png)

![image](https://user-images.githubusercontent.com/35491086/174503058-5feff7c3-eab2-474b-82cd-6992e623aa12.png)

2022-06-20 18:01 UTC, andy-about-andy commented
> 

Алексей, я исправил ошибки, но после опубликования...ничего не обновилось?! я не про код, а про визуальную часть.

2022-06-21 15:13 UTC, Zakamsky approved these changes
Отличная работа над ошибками, идем дальше!

2022-06-21 15:13 UTC, merged