Реализовывает просмотр фотографий в полноразмерном режиме
htmlacademy-javascript/1970833-kekstagram-26 pull request #6
Opened 2022-06-24 12:41 UTC by andy-about-andy

2022-06-24 12:53 UTC, andy-about-andy commented on js/rendering-thumbnails.js
> +    pictureClone.querySelector('.picture__comments').textContent = comments.length;
Алексей, нужна помощь. 
Уже несколько раз переделал домашку, в итоге на миниатюрных картинках не показывает количество комментариев. Когда открывается большая картинка, то комментарии не генерируются.
![кекстаграм](https://user-images.githubusercontent.com/96020404/175539738-0200f636-eaf5-4ccf-812e-257af1e0ecf4.png)

2022-06-25 00:01 UTC, Zakamsky requested changes
Ты хорошо постарался, ничего страшного что в паре мест запутался.

На вопрос ответил, кстати вот как я искал истину, если интересно:
- вывел в консоль массив с постами и увидел что у комментов пустой массив.
- вывел отдельно генерацию постов и генерацию коментов, убедился что методы работают по разному.
- внимательно поискал глазами разницу.

2022-06-25 19:49 UTC, andy-about-andy commented on js/full-picture.js
> +    commentFragment.append(commentClone);
Алексей, не совсем понял, почему твой вариант проще. Твой вариант я написал, но закомментировал. Получилось сильно больше строк. Или я что-то упускаю и есть подводные камни?

2022-06-25 20:43 UTC, Zakamsky commented
Хорошо поработал над ошибками. Теперь все работает корректно.

2022-06-25 20:43 UTC, merged