Правда или действие (часть 1)
htmlacademy-javascript/1970833-kekstagram-26 pull request #7
Opened 2022-06-29 19:05 UTC by andy-about-andy

---
:mortar_board: [Правда или действие (часть 1)](https://up.htmlacademy.ru/javascript/26/user/1970833/tasks/15)

:boom: https://htmlacademy-javascript.github.io/1970833-kekstagram-26/7/

2022-06-29 19:14 UTC, andy-about-andy commented on js/form-upload.js
> +    // eslint-disable-next-line no-use-before-define
Выдаёт error, хотя сделал как в скринкасте. Или всё же что-то перепутал?

2022-06-30 18:48 UTC, Zakamsky requested changes
Указал большинство ошибок, который мешали открыть форму.
Предлагаю попробовать самостоятельно разобраться что не так с валидацией... там осталось совсем чуть чуть.

решения с методами внутри проверок валидации у тебя неплохие.

кстати форма отправляется пустой, это явное нарушение.

2022-06-30 18:48 UTC, Zakamsky commented on js/form-upload.js
> +};
просто ты вызываешь функцию до ее объявления, а это стрелочная функция они не всплывают.
варианта два:
1. использовать декларирование функции, для всплытия
2. поправить порядок объявление и вызовов.

2022-06-30 18:48 UTC, Zakamsky commented on js/form-upload.js
> +  imgUpload.classList.remove('.hidden');
методы объекта `classList` принимают строку, а не селектор.
т.е. они и так среди классов ищут а с таким аргументом мы ищем и пытаемся убрать класс: `.hidden`
но такого нет, есть `hidden`

2022-07-01 08:38 UTC, andy-about-andy commented on js/form-upload.js
> +  imgUpload.classList.remove('.hidden');
спасибо, буду внимательнее

2022-07-02 16:21 UTC, Zakamsky approved these changes
В целом хорошо, все работает.
Есть конечно пара замечаний... но их вполне можно исправить в следующих ветках так что - принято!

2022-07-02 16:21 UTC, Zakamsky commented on js/main.js
> +import './form-upload.js';
кажется мы это уже обсуждали.
такой способ импортов добавит нам проблем в будущем, т.к. момент выполнения его кода неконтролируемый, что если бы мы работали с данными которые создаются только в этом файле?
лучше будет обернуть всю логику модуля в функцию, скажем `initFromHandler` и туту ее вызвать.

2022-07-02 16:21 UTC, Zakamsky commented on js/form-upload.js
> +pristine.addValidator(textHashtags, validateTextHashtags, 'Неправильно введён хэш-тэг');
мы могли бы каждую проверку сделать отдельной функцией и повторить эту строку с разными функциями и разным текстом.
так мы могли бы помочь пользователю понять как исправить свои ошибки ввода

2022-07-02 16:21 UTC, merged